# Generated by Django 4.0.1 on 2022-01-13 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='заголовок')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Categorys',
                'verbose_name_plural': 'Categorys',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='заголовок')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='URL')),
                ('content', models.TextField(blank=True, max_length=1000, verbose_name='текст')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='фото')),
                ('time_create', models.TimeField(auto_now_add=True, verbose_name='дата создания')),
                ('time_update', models.TimeField(auto_now=True, verbose_name='дата изминения')),
                ('is_published', models.BooleanField(default=True, verbose_name='публикация')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='news.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'Posts',
                'verbose_name_plural': 'Posts',
                'ordering': ['-time_update', 'pk'],
            },
        ),
    ]
